<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.1.2 (Python 3.7.4 on win32)" generated="20200102 16:13:06.087" rpa="false">
<suite id="s1" name="Magenic Sample" source="C:\Users\brownt\git\MagenicSample\magenic_sample.robot">
<test id="s1-t1" name="Test title 1">
<kw name="Get Datetime" library="my_code">
<assign>
<var>${DateTime}</var>
</assign>
<msg timestamp="20200102 16:13:06.354" level="INFO">${DateTime} = Y2020m01dH16M13S06</msg>
<status status="PASS" starttime="20200102 16:13:06.353" endtime="20200102 16:13:06.354"></status>
</kw>
<kw name="Log To Console" library="BuiltIn">
<doc>Logs the given message to the console.</doc>
<arguments>
<arg>${DateTime}</arg>
</arguments>
<status status="PASS" starttime="20200102 16:13:06.354" endtime="20200102 16:13:06.355"></status>
</kw>
<kw name="Open Browser" library="SeleniumLibrary">
<doc>Opens a new browser instance to the given ``url``.</doc>
<arguments>
<arg>http://www.magenic.com</arg>
<arg>${Browser}</arg>
</arguments>
<msg timestamp="20200102 16:13:06.355" level="INFO">Opening browser 'chrome' to base url 'http://www.magenic.com'.</msg>
<status status="PASS" starttime="20200102 16:13:06.355" endtime="20200102 16:13:12.813"></status>
</kw>
<tags>
<tag>DEBUG</tag>
<tag>TopLevel</tag>
</tags>
<status status="PASS" starttime="20200102 16:13:06.353" endtime="20200102 16:13:12.814" critical="yes"></status>
</test>
<doc>Magenic Sample App</doc>
<status status="PASS" starttime="20200102 16:13:06.089" endtime="20200102 16:13:12.815"></status>
</suite>
<statistics>
<total>
<stat pass="1" fail="0">Critical Tests</stat>
<stat pass="1" fail="0">All Tests</stat>
</total>
<tag>
<stat pass="1" fail="0">DEBUG</stat>
<stat pass="1" fail="0">TopLevel</stat>
</tag>
<suite>
<stat pass="1" fail="0" id="s1" name="Magenic Sample">Magenic Sample</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20200102 16:13:06.335" level="ERROR">Error in file 'C:\Users\brownt\git\MagenicSample\magenic_sample.robot': Importing test library 'C:\Users\brownt\git\MagenicSample\website_functions.py' failed: ModuleNotFoundError: No module named 'website_functions'
Traceback (most recent call last):
  None
PYTHONPATH:
  c:\program files\python37\scripts\robot.exe
  C:\Program Files\Python37
  c:\users\brownt\PycharmProjects\AppiumExperiment
  c:\users\brownt\PycharmProjects\AppiumExperiment\src
  C:\Users\brownt\git\MagenicSample
  c:\program files\python37\python37.zip
  c:\program files\python37\DLLs
  c:\program files\python37\lib
  c:\program files\python37\lib\site-packages
  c:\program files\python37\lib\site-packages\win32
  c:\program files\python37\lib\site-packages\win32\lib
  c:\program files\python37\lib\site-packages\Pythonwin</msg>
</errors>
</robot>
